config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'login/index'

  get 'home/index'

  get 'submissions/index'

  get 'submissions/thankyou'

  #reroute after searching
  get 'home/submissions' => 'submissions#index'


  resource :home
  resources :submissions do
    member { get :approvereview }
  end


  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root "login#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord

	validates :rating, presence: true
	validates :season, presence: true
	validates :year, presence: true
	validates :compensation, presence: true
	validates :country, presence: true
	validates :positionTitle, presence: true
	validates :hours, presence: true
	validates :organizationName, presence: true
	validates :mailingAddress, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zipcode, presence: true
	validates :organizationMission, presence:true
	validates :organizationRecommendation, presence: true

	scope :approved, -> {
		where(:submissionReview => true)
	}
	scope :pending, -> {
		where(:submissionReview => false)
	}

	def self.search(search, compensationSearch, locationSearch)
		# if search
		positions = Submission.where('"positionTitle" LIKE ? AND city LIKE ? AND compensation LIKE ?', "%#{search}%", "%#{locationSearch}%", "%#{compensationSearch}") 

		return positions

	end

end

app/models/user.rb
class User < ApplicationRecord

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.name
			user.oauth_token = auth.credentials.token
			user.oauth_expires_at = Time.at(auth.credentials.expires_at)
			user.save!
		end
		
		#add user admin check
		if user.name == "Shirley He"
			user.admin =  true
		else
			user.admin = false
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authenticate_user
		if session[:user_id] == nil
			redirect_to(:controller => 'login', :action => 'index')
			return false
		else
			return true	
		end
	end

	def save_login_state
		if session[:user_id]
			flash[:error] = "You must logout to leave!"
			redirect_to(:controller => 'home', :action => 'index')
			return false
		else
			return true
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	before_filter :save_login_state, :only => [:index]
	def index
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to controller: "home", action:"index"
	end

	def destroy
		session[:user_id] = nil
		redirect_to controller: "login", action:"index"
	end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  before_filter :authenticate_user

  def index
    #admin
    @current_user = User.find_by id: session[:user_id]
    if @current_user.name == "Shirley He"
      @current_user.update_attribute :admin, true
      @submissions = Submission.all
      if params[:search]
        @submissions = Submission.search(params[:search],params[:compensationSearch],params[:locationSearch])
      end

    #SORT
    if params[:sorting] == '"positionTitle"'
     @submissions = @submissions.order('"positionTitle" ASC')
   elsif params[:sorting] == 'rating'
    @submissions = @submissions.order('rating ASC')
  elsif params[:sorting] == '"organizationName"'
    @submissions = @submissions.order('"organizationName" ASC')
  elsif params[:sorting] == 'city'
    @submissions = @submissions.order('city ASC')
  elsif params[:sorting] == 'compensation'
    @submissions = @submissions.order('compensation ASC')
  elsif params[:sorting] == 'year'
    @submissions = @submissions.order('year ASC')
    #Industry sorting.....
  elsif params[:sorting] == 'agriculture'
    @submissions = @submissions.order('agriculture ASC')
  end

else


 @submissions = Submission.where(submissionReview: true)
    #SEARCH
    if params[:search]
      @submissions = Submission.where(submissionReview: true).search(params[:search],params[:compensationSearch],params[:locationSearch])
    end

    #SORT
    if params[:sorting] == '"positionTitle"'
     @submissions = @submissions.order('"positionTitle" ASC')
   elsif params[:sorting] == 'rating'
    @submissions = @submissions.order('rating ASC')
  elsif params[:sorting] == '"organizationName"'
    @submissions = @submissions.order('"organizationName" ASC')
  elsif params[:sorting] == 'city'
    @submissions = @submissions.order('city ASC')
  elsif params[:sorting] == 'compensation'
    @submissions = @submissions.order('compensation ASC')
  elsif params[:sorting] == 'year'
    @submissions = @submissions.order('year ASC')
    #Industry sorting.....
  elsif params[:sorting] == 'agriculture'
    @submissions = @submissions.order('agriculture ASC')
  end
end
end

def new
 @submission = Submission.new
end


def create
 @submission = Submission.new(params.require(:submission).permit(:positionTitle,
  :hours, :organizationName, :mailingAddress, :city, :zipcode, :rating, :season,
  :year, :compensation, :state, :country, :organizationURL, :organizationContactName,
  :organizationContactJobTitle, :organizationContactEmail, :outsideCompensation,
  :cardinalInternship, :wesAlum, :organizationMission, :organizationRecommendation,
  :agriculture, :architecture, :artsEntertainment, :education, :energy, :financialServices,
  :foodBeverageCPG, :government, :healthcare, :hospitality, :manufacturing, :mediaMarketing,
  :nonProfit, :pharma, :professionalServices, :retailStores, :technology, :transportation, :other))
 if @submission.save
      AddReviewMailer.addreviewmailer_email(@submission).deliver
      flash[:success] = "SENT EMAIL"
      render 'thankyou'
      return
    else
      render "new"
    end
  end


  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    if @submission.update(submission_params)
    render 'show'
  else
    render 'edit'
  end
end


def show
  @submission = Submission.find(params[:id])
end

def thankyou
end

#approving review through email...
def approvereview
  @submission = Submission.find(params[:id])
  if @submission.update_attribute(:submissionReview, true)
    #send mailer
    @current_user = User.find_by id: session[:user_id]
    AddReviewMailer.approvereviewmailer_email(@current_user).deliver
    render 'show'
  else
    render 'edit'
  end
end


def destroy
  @submission = Submission.find(params[:id])
  if @submission.destroy
      #redirect_to root_path
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "Error deleting"
    end
  end

  private
  def set_submission
    @submission = Submission.find(params[:positionTitle, :compensation, :city])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/login/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Google Auth Example App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->
  <link href="/assets/custom.css?body=1" media="screen" rel="stylesheet">
  <link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">
  <link href='//fonts.googleapis.com/css?family=Pathway Gothic One' rel='stylesheet'>
  <link href='//fonts.googleapis.com/css?family=EB Garamond' rel='stylesheet'>

</head>


<style media="screen">

  h1{
    font-family: 'EB Garamond';
    font-weight: lighter;
    font-size: 40px;
  }

  h4{
    font-family: 'Pathway Gothic One';
    font-weight: lighter;
    font-size: 25px;
    font-weight: lighter;
  }
  body {
    background-image: url(/assets/background.jpg);
    background-size: cover;
  }



  @media (min-width: 768px) {
    .container-fluid {
      margin-top: 250px;
      max-width: 1000px;
      color: white;
      text-align: center;
    }
  }
  .container-narrow > hr {
    margin: 30px 0;
  }

  .row{
    margin-bottom: 10px;
    margin-top: 10px;
  }

  .change-height{
    margin-top: 25px;
  }

  .searchclass {
    text-align: left;
  }

  .height {
    height: 120%;
  }
</style>


<body>

  <div class="container-fluid">
    <h1>WESLEYAN STUDENT INTERNSHIP REVIEWS</h1>
    <div class="height">
      <h4>By Wes students for Wes students</h4>
    </div>

    <div>
      <% if current_user %>
      Signed in as <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
      <h4><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in", class: 'btn btn-primary' %></h4>
      <% end %>
    </div>

  </div>
</body>
</html>

app/views/submissions/edit.html.erb
<h1> Edit Submission </h1>

<%= form_for @submission do |f| %>


<%= link_to("New", new_submission_path(@submission.id)) %>

<%= link_to 'Back', submissions_path %>

<% end %>

app/views/submissions/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>Bootstrap 101 Template</title>

	<!-- Bootstrap -->
	<link href="/assets/custom.css?body=1" media="screen" rel="stylesheet">
	<link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">
	<link href='//fonts.googleapis.com/css?family=Pathway Gothic One' rel='stylesheet'>
	<link href='//fonts.googleapis.com/css?family=EB Garamond' rel='stylesheet'>
</head>

<style media="screen">
	.header {
		width:100%;
		position:fixed;
		left: 0; right: 0;
		top: 0;
		z-index: 1;
	}

	.headcontainer {
		color: black;
		height: 60px;
		line-height: 75px;
	}
	.head{
		font-family: 'EB Garamond';
		font-weight: lighter;
		font-size: 37px;
		color: white;
	}
	.head:hover {
		color: white;
		text-decoration: none;
	}
	.signout {
		color: white;
		font-size: 14px;
	}

	.search-title{
		background-color: #8B0000;
		color: white;
		width: 100%;
		height: 50%;
		text-align: left;

	}

	.tabletitle {
		color: white;
	}
	.tabletitle:hover {
		color: white;
	}

	*{
		font-family: 'Pathway Gothic One';
		font-size: 21px;
	}
	table, th, td{

	}
	td{
		color: black;
		background-color: white;
	}
	.container {
		width: 100%;
	}
	.descr {
		text-align: left;
	}


	.form-check-label {
		font-size: 12px;
	}



	.parent {
		background-color: black;
		color: white;
		width: 100%;
		height: 200%;
		display: table;
		text-align: center;

	}
	.parent > .child {
		display: table-cell;
		vertical-align: middle;
	}



	#parent2 {
		display: table;
	}
	#child2 {
		display: table-cell;
		vertical-align: middle;
	}



	.title-text {
		margin-left: 10px;
		font-size: 25px;
	}

	.left {
		float: left;
	}
	.display {
		border: solid 0.5px;
	}

	#sign {
		text-align: right;
	}
	.searchbutton {
		width: 45%;
		height: 45%;
	}

</style>

<body>
	<div class="container">
		<div class="header">
			<section class="parent">
				<div class="child row">
					<div class="headcontainer">
						<%= content_tag :div, class: "col-md-11" do -%>
						<%= link_to "WESLEYAN STUDENT INTERNSHIP REVIEWS", home_index_path, class: "head" %>
						<% end %>
						<%= content_tag :div, class: "col-md-1" do -%>
						<%= link_to "Sign out", signout_path, id: "sign_out", class: "signout" %>
						<% end -%>
					</div>
					<div class="search-title">
						<h3 style="font-size: 35px; margin-left: 5px;">SEARCH RESULTS</h3>
					</div>
				</div>
			</section>
		</div>




		<div class="submission">
			<div class="container" style="margin-top: 150px;">
				<div class="row" style="text-align:center; width: 100%;">
					<!-- Keyword Search -->
					<%= form_tag('submissions#index', :method => "get", id: "search-form") do %>

					<div class="col-md-3 ">

						<%= text_field_tag :search, params[:search], placeholder: "Internship title", class: 'form-control' %>
					</div>

					<!-- Location Search -->
					<div class="col-md-3 ">
						<%= text_field_tag :locationSearch, params[:locationSearch], placeholder: "Location (City)", class: 'form-control' %>
					</div>

					<!-- Industry/Field Search -->
					<div class="col-md-3 ">
						<%= select_tag "industrySearch", options_for_select(["Agriculture & Natural Resources", "Architecture, Real Estate & Construction",
							"Arts, Entertainment & Recreation","Education",
							"Energy", "Financial Services",
							"Food, Beverage & CPG",
							"Government, Law & Politics",
							"Healthcare & Services",
							"Hospitality",
							"Manufacturing", "Media & Marketing", "Non-Profit",
							"Pharma & Medical Devices", "Professional Services",
							"Retail Stores & Trade", "Technology",
							"Transportation & Logistics"],
							params[:industrySearch]), class: 'form-control', prompt: "Industry/Field" %>
						</div>

						<!-- Compensation Search -->
						<div class="col-md-2 ">
							<%= select_tag "compensationSearch", options_for_select(["Unpaid", "Paid", "Stipend"],
							params[:compensationSearch]), class: 'form-control', prompt: "Compensation" %>
						</div>


						<!-- Search button -->
						<div class="col-md-1 searchclass">
							<%= image_submit_tag ("/assets/search.png"), class: 'searchbutton' %>
						</div>

						<% end %>

					</div>


					<% if @submissions.blank? %>
					<h4 style="text-align: center">There are no quotes containing the term <%= params[:search] %> <%= params[:compensationSearch] %>
						<%= params[:locationSearch] %>
					</h4>

					<% else %>
					<div class="container" style="margin-top: 25px;">


						<div class="col-md-12">
							<div class="network">
								<div class="search-title" id="parent2">
									<div id="child2">
										<table class="table table-bordered" style="width:100%; text-align: center;">
											<thead>
												<tr>
													<!-- Sort by Position Title -->
													<th style="text-align:center"><%= link_to "Position Title ⇂", submissions_path(:sorting => 'positionTitle'), class: "tabletitle"%></th>
													<!-- Sort by Rating -->
													<th style="text-align:center"><%= link_to "Rating ⇂", submissions_path(:sorting => 'rating'), class: "tabletitle"%></th>
													<!-- Sort by Industry -->
													<th style="text-align:center"><%= link_to "Industry ⇂", submissions_path(:sorting => 'agriculture'), class: "tabletitle"%></th>
													<!-- Sort by Organization -->
													<th style="text-align:center"><%= link_to "Organization ⇂", submissions_path(:sorting => 'organizationName'), class: "tabletitle"%></th>
													<!-- Sort by Location -->
													<th style="text-align:center"><%= link_to "Location ⇂", submissions_path(:sorting => 'city'), class: "tabletitle"%></th>
													<!-- Sort by Compensation -->
													<th style="text-align:center"><%= link_to "Compensation ⇂", submissions_path(:sorting => 'compensation'), class: "tabletitle"%></th>
													<!-- Sort by Date -->
													<th style="text-align:center"><%= link_to "Date ⇂", submissions_path(:sorting => 'year'), class: "tabletitle"%></th>
													<th style="text-align:center", class: "tabletitle"> Admin: </th> 
													
												</tr>
											</thead>
											<tbody>

											<% if current_user.admin %>
												<% @submissions.each do |submission| %>
												<tr>
													<td><%= link_to submission.positionTitle, submission %></td>
													<td><%= submission.rating %></td>
													<!-- <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->

													<!-- <td><%= link_to 'Edit', edit_submission_path(submission) %></td> -->


													<!-- Do all industry boolean searching manually......... -->
													<td><% if  submission.agriculture  %>
														Agriculture
														<% end %>
														<% if  submission.architecture  %>
														Architecture
														<% end %>
														<% if  submission.artsEntertainment %>
														Arts/Entertainment
														<% end %>
														<% if  submission.education  %>
														Education
														<% end %>
														<% if  submission.energy  %>
														Energy
														<% end %>
														<% if  submission.financialServices  %>
														Financial Services
														<% end %>
														<% if  submission.foodBeverageCPG  %>
														Food/Beverage
														<% end %>
														<% if  submission.government  %>
														Government
														<% end %>
														<% if  submission.healthcare  %>
														Healthcare
														<% end %>
														<% if  submission.hospitality  %>
														Hospitality
														<% end %>
														<% if  submission.manufacturing  %>
														Manufacturing
														<% end %>
														<% if  submission.mediaMarketing  %>
														Media Marketing
														<% end %>
														<% if  submission.nonProfit  %>
														Non-Profit
														<% end %>
														<% if  submission.pharma  %>
														Pharmaceutical
														<% end %>
														<% if  submission.professionalServices  %>
														Professional Services
														<% end %>
														<% if  submission.retailStores  %>
														Retail Stores
														<% end %>
														<% if  submission.technology %>
														Technology
														<% end %>
														<% if  submission.transportation  %>
														Transportation
														<% end %>
														<% if  submission.other  %>
														Other

														<% end %>
													</td>


													<!-- All other fields -->
													<td><%= submission.organizationName %></td>
													<td><%= submission.city %></td>
													<td><%= submission.compensation %></td>
													<td><%= submission.season %>    <%=submission.year.to_s.slice(0..3) %>  </td>
													<!-- show unapproved reviews -->
													<td>
														<% if submission.submissionReview == false %>
														<%= link_to "Approve", approvereview_submission_url(submission)%> / <%= link_to 'Deny', submission, method: :delete, data: { confirm: 'Are you sure?' } %>



														<% end %></td>


													



												</tr>
												<% end %>

												<% else %>
														<% @submissions.each do |submission| %>
												<tr>
													<td><%= link_to submission.positionTitle, submission %></td>
													<td><%= submission.rating %></td>
													<!-- <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->

													<!-- <td><%= link_to 'Edit', edit_submission_path(submission) %></td> -->


													<!-- Do all industry boolean searching manually......... -->
													<td><% if  submission.agriculture  %>
														Agriculture
														<% end %>
														<% if  submission.architecture  %>
														Architecture
														<% end %>
														<% if  submission.artsEntertainment %>
														Arts/Entertainment
														<% end %>
														<% if  submission.education  %>
														Education
														<% end %>
														<% if  submission.energy  %>
														Energy
														<% end %>
														<% if  submission.financialServices  %>
														Financial Services
														<% end %>
														<% if  submission.foodBeverageCPG  %>
														Food/Beverage
														<% end %>
														<% if  submission.government  %>
														Government
														<% end %>
														<% if  submission.healthcare  %>
														Healthcare
														<% end %>
														<% if  submission.hospitality  %>
														Hospitality
														<% end %>
														<% if  submission.manufacturing  %>
														Manufacturing
														<% end %>
														<% if  submission.mediaMarketing  %>
														Media Marketing
														<% end %>
														<% if  submission.nonProfit  %>
														Non-Profit
														<% end %>
														<% if  submission.pharma  %>
														Pharmaceutical
														<% end %>
														<% if  submission.professionalServices  %>
														Professional Services
														<% end %>
														<% if  submission.retailStores  %>
														Retail Stores
														<% end %>
														<% if  submission.technology %>
														Technology
														<% end %>
														<% if  submission.transportation  %>
														Transportation
														<% end %>
														<% if  submission.other  %>
														Other

														<% end %>
													</td>


													<!-- All other fields -->
													<td><%= submission.organizationName %></td>
													<td><%= submission.city %></td>
													<td><%= submission.compensation %></td>
													<td><%= submission.season %>    <%=submission.year.to_s.slice(0..3) %>  </td>




												</tr>
												<% end %>
												<% end %>

											</tbody>

										</table>
									</div>
								</div>
							</div>
						</div>
						<% end %>

					</div>
				</div>
			</div>
		</div>



		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="js/bootstrap.min.js"></script>



	</body>
	</html>

app/views/submissions/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->
  <link href="/assets/custom.css?body=1" media="screen" rel="stylesheet">
  <link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">
  <link href='//fonts.googleapis.com/css?family=Pathway Gothic One' rel='stylesheet'>
  <link href='//fonts.googleapis.com/css?family=EB Garamond' rel='stylesheet'>
</head>

<style media="screen">
.header {
  width:100%;
  position:fixed;
  left: 0; right: 0;
  top: 0;
  z-index: 1;
}
.headcontainer {
  color: black;
  height: 60px;
  line-height: 75px;
}
.head{
  font-family: 'EB Garamond';
  font-weight: lighter;
  font-size: 37px;
  color: white;
}
.head:hover {
  color: white;
  text-decoration: none;
}
.signout {
  color: white;
  font-size: 14px;
}

*{
  font-family: 'Pathway Gothic One';
  font-size: 21px;
  letter-spacing: 0.4px;
}
.row{
  margin-bottom: 10px;
  margin-top: 20px;
  /*push down the top!!*/
}
.parent {
  background-color: black;
  color: white;
  width: 100%;
  height: 200%;
  display: table;
  text-align: center;
}
.parent > .child {
  display: table-cell;
  vertical-align: middle;
}
.search-title{
  background-color: #8B0000;
  color: white;
  width: 100%;
  height: 50%;
  text-align: left;
  border: 2px solid black;
  border-bottom: none;
}
.top-title{
  background-color: #8B0000;
  color: white;
  width: 100%;
  height: 50%;
  text-align: left;
}
#sign {
  text-align: right;
}

/*above: need for every page */

.container {
  width: 90%;
}
.descr {
  text-align: left;
}


.form-check-label {
  font-size: 12px;
}


#bigtitle {
  margin-left: 10px;
}

#parent2 {
  display: table;
}
#child2 {
  display: table-cell;
  vertical-align: middle;
}



.title-text {
  margin-left: 10px;
}

.left {
  float: left;
}
.display {
  border: solid 2px;
  padding-left: 5px;
}
.pictureholder {
  background: black;
  height: 200px;
  margin-bottom: 30px;
  margin-top: 10px;
}
.general {
  line-height: 0.7;
  font-size: 40px;
  font-weight: bolder;
}



</style>

<body>
  <div class="header">
    <section class="parent">
      <div class="child row">
        <div class="headcontainer">
          <%= content_tag :div, class: "col-md-11" do -%>
            <%= link_to "WESLEYAN STUDENT INTERNSHIP REVIEWS", home_index_path, class: "head" %>
          <% end -%>
          <%= content_tag :div, class: "col-md-1" do -%>
            <%= link_to "Sign out", signout_path, id: "sign_out", class: "signout" %>
          <% end -%>
        </div>


        <div class="top-title">
          <h3 style="font-size: 35px; margin-left: 5px;">INTERNSHIP DETAILS</h3>
        </div>
      </div>
    </section>
  </div>


  <div class="submission">
    <div class="row multi-column" style="margin-top: 150px;">

      <div class="container">
        <div class="col-md-6">
          <!-- general information -->
          <div class="general">
            <div class="general">
              <p class= "general">
                <p class="general"><%= @submission.positionTitle %></p>
                <p class="general"><%= @submission.organizationName %> <%= @submission.rating %>
                <p class="general"><% if @submission.state != "N/A" %>
                  <%= @submission.city %>, <%= @submission.state %>, <%= @submission.country %>
                  <% else %>
                  <%= @submission.city %>, <%= @submission.country %>
                  <% end %></p>
                <p class="general"><%= @submission.compensation %></p>
                <p class="general">Organization link: <%= link_to @submission.organizationURL, "http://#{@submission.organizationURL}", style: "font-size: 35px; color: black; text-decoration: underline;" %></p>
              </p>
            </br>
            </div>
          </div>

          <!-- Experience review -->
          <div class="exp">
            <div class="search-title" id="parent2">
              <div id="child2"><h3 class="title-text">Experience Review</h3></div>
            </div>
            <div class="display">
              <!-- needs a default msg when empty -->
              <%= @submission.organizationRecommendation %>
            </div>
          </div>
        </div>


        <div class="col-md-6">
          <div class="network">
            <div class="search-title" id="parent2">
              <div id="child2"><h3 class="title-text">Wesleyan Network Information</h3></div>
            </div>
            <div class="display">
            <!-- if else instead of boolean display -->
              <p>Was this a Cardinal internship:
              <% if @submission.cardinalInternship %>
              Yes
              <% else %>
              No
              <% end %>
              </p>

              <p>Is the contact a Wes alum:
              <% if @submission.wesAlum %> Yes
              <% else %>
              No
              <% end %>

              </p>
           <!--    <p>Wesleyan student contact email: <%= @submission.organizationContactEmail %></p> -->

            </div>
          </div>
        </br>
        <div class="mission">
          <div class="search-title" id="parent2">
            <div id="child2"><h3 class="title-text">Organization Mission</h3></div>
          </div>
          <div class="display">
            <%= @submission.organizationMission %>

          </div>
        </div>
      </br>
      <div class="contact">
        <div class="search-title" id="parent2">
          <div id="child2"><h3 class="title-text">Organization Contact Information</h3></div>
        </div>
        <div class="display">
          <p>Contact name: <%= @submission.organizationContactName %></p>
          <p>Contact title: <%= @submission.organizationContactJobTitle %></p>
          <p>Contact email: <%= @submission.organizationContactEmail %></p>
        </div>
      </div>
    </div>
  </div>

</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>



</body>

</html>